#include "margin_proofs.h"
#include <lean/lean.h>
#include <stdint.h>

/* Forward declarations for Lean runtime functions (might not be in lean.h) */
void lean_initialize(void);
void lean_io_mark_end_initialization(void);

/* Lean-exported functions from our Core.lean */
extern lean_object* lean_trade_reward(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
extern lean_object* lean_trade_balance(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);
extern lean_object* lean_trade_position(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*);

/* Module initialization function generated by Lean */
extern lean_object* initialize_margin__proofs_MarginProofs_Core(uint8_t builtin);

/* Lean runtime initialization */
void margin_proofs_init(void) {
    lean_initialize();
    lean_object* res = initialize_margin__proofs_MarginProofs_Core(1);
    /* Clean up the initialization result if it's an object */
    if (res && !lean_is_scalar(res)) lean_dec(res);
    lean_io_mark_end_initialization();
}

/* Helper to convert int64_t to Lean Int */
static inline lean_object* to_lean(int64_t val) {
    return lean_int64_to_int(val);
}

/* Helper to convert Lean Int to int64_t (cast uint64_t to int64_t) */
static inline int64_t from_lean(lean_object* obj) {
    return (int64_t)lean_int64_of_int(obj);
}

int64_t c_trade_reward(int64_t b, int64_t p, int64_t pr, int64_t q, int64_t pp) {
    lean_object* r = lean_trade_reward(to_lean(b), to_lean(p), to_lean(pr), to_lean(q), to_lean(pp));
    int64_t res = from_lean(r);
    lean_dec(r);
    return res;
}

int64_t c_trade_balance(int64_t b, int64_t p, int64_t pr, int64_t q) {
    lean_object* r = lean_trade_balance(to_lean(b), to_lean(p), to_lean(pr), to_lean(q), to_lean(0));
    int64_t res = from_lean(r);
    lean_dec(r);
    return res;
}

int64_t c_trade_position(int64_t b, int64_t p, int64_t pr, int64_t q) {
    lean_object* r = lean_trade_position(to_lean(b), to_lean(p), to_lean(pr), to_lean(q), to_lean(0));
    int64_t res = from_lean(r);
    lean_dec(r);
    return res;
}